server {
   charset utf-8;
   client_max_body_size 128M;
   sendfile off;

   listen 80; ## listen for ipv4

   server_name yii2basic.test;
   root        /app/web/;
   index       index.php;

   access_log  /app/vagrant/nginx/log/yii2basic.access.log;
   error_log   /app/vagrant/nginx/log/yii2basic.error.log;

   location / {
       try_files $uri $uri/ /index.php$is_args$args;
   }

   location ~ \.php$ {
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
       try_files $uri =404;
   }

   location ~ /\.(ht|svn|git) {
       deny all;
   }
}
